### ISSUE TITLE
Error in FocalLoss

### ISSUE THREAD

**Issue by JunMa11** [Hsuxu/Loss_ToolBox-PyTorch#6]
Dear @Hsuxu ,

Thanks for sharing the code.

An error occurred when running `FocalLoss_test.py`.
```
    if alpha.device != input.device:
AttributeError: 'builtin_function_or_method' object has no attribute 'device'
```

https://github.com/Hsuxu/Loss_ToolBox-PyTorch/blob/7c1f9d86e7d28670fd708d0a32e89bd8ba42ee50/FocalLoss/FocalLoss.py#L64

**Comment by ccyyy** [comment]
check whether it is a tensor

**Comment by JunMa11** [comment]
It should be `target` or `logit`, rather than `input`, here
https://github.com/Hsuxu/Loss_ToolBox-PyTorch/blob/7c1f9d86e7d28670fd708d0a32e89bd8ba42ee50/FocalLoss/FocalLoss.py#L64
